# frozen_string_literal: true

plugins:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-thread_safety

inherit_gem:
  standard: config/base.yml
  standard-performance: config/base.yml
  standard-minitest: config/base.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - bin/**/*
    - "*.gemspec"
    - vendor/**/*

Layout/LineLength:
  Max: 100

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space

Style/MixinUsage:
  Exclude:
    - test/**/*

ThreadSafety/ClassAndModuleAttributes:
  Enabled: false

ThreadSafety/ClassInstanceVariable:
  Enabled: false

ThreadSafety/NewThread:
  Enabled: false
